/* Generado por generar-galeria.command — no editar a mano. */
const PHOTOS = [
  { src: "assets/img/gallery/muay-thai-1.jpg", tags: ["Muay Thai"], alt: "Muay Thai 1" },
  { src: "assets/img/gallery/muay-thai-2.jpg", tags: ["Muay Thai"], alt: "Muay Thai 2" },
  { src: "assets/img/gallery/muay-thai-3.jpg", tags: ["Muay Thai"], alt: "Muay Thai 3" },
  { src: "assets/img/gallery/muay-thai-4.jpg", tags: ["Muay Thai"], alt: "Muay Thai 4" },
  { src: "assets/img/gallery/muay-thai-5.jpg", tags: ["Muay Thai"], alt: "Muay Thai 5" },
  { src: "assets/img/gallery/muay-thai-6.jpg", tags: ["Muay Thai"], alt: "Muay Thai 6" },
  { src: "assets/img/gallery/muay-thai-7.jpg", tags: ["Muay Thai"], alt: "Muay Thai 7" },
  { src: "assets/img/gallery/muay-thai-8.jpg", tags: ["Muay Thai"], alt: "Muay Thai 8" },
  { src: "assets/img/gallery/muay-thai-9.jpg", tags: ["Muay Thai"], alt: "Muay Thai 9" },
  { src: "assets/img/gallery/muay-thai-10.jpg", tags: ["Muay Thai"], alt: "Muay Thai 10" },
  { src: "assets/img/gallery/muay-thai-11.jpg", tags: ["Muay Thai"], alt: "Muay Thai 11" },
  { src: "assets/img/gallery/muay-thai-12.jpg", tags: ["Muay Thai"], alt: "Muay Thai 12" },
  { src: "assets/img/gallery/muay-thai-13.jpg", tags: ["Muay Thai"], alt: "Muay Thai 13" },
  { src: "assets/img/gallery/muay-thai-14.jpg", tags: ["Muay Thai"], alt: "Muay Thai 14" },
  { src: "assets/img/gallery/muay-thai-15.jpg", tags: ["Muay Thai"], alt: "Muay Thai 15" },
  { src: "assets/img/gallery/muay-thai-16.jpg", tags: ["Muay Thai"], alt: "Muay Thai 16" },
  { src: "assets/img/gallery/muay-thai-17.jpg", tags: ["Muay Thai"], alt: "Muay Thai 17" },
  { src: "assets/img/gallery/muay-thai-18.jpg", tags: ["Muay Thai"], alt: "Muay Thai 18" },
  { src: "assets/img/gallery/muay-thai-19.jpg", tags: ["Muay Thai"], alt: "Muay Thai 19" },
  { src: "assets/img/gallery/muay-thai-20.jpg", tags: ["Muay Thai"], alt: "Muay Thai 20" },
  { src: "assets/img/gallery/muay-thai-21.jpg", tags: ["Muay Thai"], alt: "Muay Thai 21" },
  { src: "assets/img/gallery/muay-thai-22.jpg", tags: ["Muay Thai"], alt: "Muay Thai 22" },
  { src: "assets/img/gallery/muay-thai-23.jpg", tags: ["Muay Thai"], alt: "Muay Thai 23" },
  { src: "assets/img/gallery/muay-thai-24.jpg", tags: ["Muay Thai"], alt: "Muay Thai 24" },
  { src: "assets/img/gallery/muay-thai-25.jpg", tags: ["Muay Thai"], alt: "Muay Thai 25" },
  { src: "assets/img/gallery/muay-thai-26.jpg", tags: ["Muay Thai"], alt: "Muay Thai 26" },
  { src: "assets/img/gallery/muay-thai-27.jpg", tags: ["Muay Thai"], alt: "Muay Thai 27" },
  { src: "assets/img/gallery/muay-thai-28.jpg", tags: ["Muay Thai"], alt: "Muay Thai 28" },
  { src: "assets/img/gallery/muay-thai-29.jpg", tags: ["Muay Thai"], alt: "Muay Thai 29" },
  { src: "assets/img/gallery/muay-thai-30.jpg", tags: ["Muay Thai"], alt: "Muay Thai 30" },
  { src: "assets/img/gallery/muay-thai-31.jpg", tags: ["Muay Thai"], alt: "Muay Thai 31" },
  { src: "assets/img/gallery/muay-thai-32.jpg", tags: ["Muay Thai"], alt: "Muay Thai 32" },
  { src: "assets/img/gallery/muay-thai-33.jpg", tags: ["Muay Thai"], alt: "Muay Thai 33" },
  { src: "assets/img/gallery/muay-thai-34.jpg", tags: ["Muay Thai"], alt: "Muay Thai 34" },
  { src: "assets/img/gallery/muay-thai-35.jpg", tags: ["Muay Thai"], alt: "Muay Thai 35" },
  { src: "assets/img/gallery/muay-thai-36.jpg", tags: ["Muay Thai"], alt: "Muay Thai 36" },
  { src: "assets/img/gallery/muay-thai-37.jpg", tags: ["Muay Thai"], alt: "Muay Thai 37" },
  { src: "assets/img/gallery/muay-thai-38.jpg", tags: ["Muay Thai"], alt: "Muay Thai 38" },
  { src: "assets/img/gallery/muay-thai-39.jpg", tags: ["Muay Thai"], alt: "Muay Thai 39" },
  { src: "assets/img/gallery/muay-thai-40.jpg", tags: ["Muay Thai"], alt: "Muay Thai 40" },
  { src: "assets/img/gallery/muay-thai-41.jpg", tags: ["Muay Thai"], alt: "Muay Thai 41" },
  { src: "assets/img/gallery/muay-thai-42.jpg", tags: ["Muay Thai"], alt: "Muay Thai 42" },
  { src: "assets/img/gallery/muay-thai-43.jpg", tags: ["Muay Thai"], alt: "Muay Thai 43" },
  { src: "assets/img/gallery/muay-thai-44.jpg", tags: ["Muay Thai"], alt: "Muay Thai 44" },
  { src: "assets/img/gallery/muay-thai-45.jpg", tags: ["Muay Thai"], alt: "Muay Thai 45" },
  { src: "assets/img/gallery/muay-thai-46.jpg", tags: ["Muay Thai"], alt: "Muay Thai 46" },
  { src: "assets/img/gallery/muay-thai-47.jpg", tags: ["Muay Thai"], alt: "Muay Thai 47" },
  { src: "assets/img/gallery/muay-thai-48.jpg", tags: ["Muay Thai"], alt: "Muay Thai 48" },
  { src: "assets/img/gallery/muay-thai-49.jpg", tags: ["Muay Thai"], alt: "Muay Thai 49" },
  { src: "assets/img/gallery/muay-thai-50.jpg", tags: ["Muay Thai"], alt: "Muay Thai 50" },
  { src: "assets/img/gallery/muay-thai-51.jpg", tags: ["Muay Thai"], alt: "Muay Thai 51" },
  { src: "assets/img/gallery/muay-thai-52.jpg", tags: ["Muay Thai"], alt: "Muay Thai 52" },
  { src: "assets/img/gallery/muay-thai-53.jpg", tags: ["Muay Thai"], alt: "Muay Thai 53" },
  { src: "assets/img/gallery/muay-thai-54.jpg", tags: ["Muay Thai"], alt: "Muay Thai 54" },
  { src: "assets/img/gallery/muay-thai-55.jpg", tags: ["Muay Thai"], alt: "Muay Thai 55" },
  { src: "assets/img/gallery/muay-thai-56.jpg", tags: ["Muay Thai"], alt: "Muay Thai 56" },
  { src: "assets/img/gallery/muay-thai-57.jpg", tags: ["Muay Thai"], alt: "Muay Thai 57" },
  { src: "assets/img/gallery/muay-thai-58.jpg", tags: ["Muay Thai"], alt: "Muay Thai 58" },
  { src: "assets/img/gallery/muay-thai-59.jpg", tags: ["Muay Thai"], alt: "Muay Thai 59" },
  { src: "assets/img/gallery/muay-thai-60.jpg", tags: ["Muay Thai"], alt: "Muay Thai 60" },
  { src: "assets/img/gallery/muay-thai-61.jpg", tags: ["Muay Thai"], alt: "Muay Thai 61" },
  { src: "assets/img/gallery/bjj-1.jpg", tags: ["BJJ"], alt: "BJJ 1" },
  { src: "assets/img/gallery/bjj-2.jpg", tags: ["BJJ"], alt: "BJJ 2" },
  { src: "assets/img/gallery/bjj-3.jpg", tags: ["BJJ"], alt: "BJJ 3" },
  { src: "assets/img/gallery/bjj-4.jpg", tags: ["BJJ"], alt: "BJJ 4" },
  { src: "assets/img/gallery/bjj-5.jpg", tags: ["BJJ"], alt: "BJJ 5" },
  { src: "assets/img/gallery/bjj-6.jpg", tags: ["BJJ"], alt: "BJJ 6" },
  { src: "assets/img/gallery/bjj-7.jpg", tags: ["BJJ"], alt: "BJJ 7" },
  { src: "assets/img/gallery/bjj-8.jpg", tags: ["BJJ"], alt: "BJJ 8" },
  { src: "assets/img/gallery/bjj-9.jpg", tags: ["BJJ"], alt: "BJJ 9" },
  { src: "assets/img/gallery/bjj-10.jpg", tags: ["BJJ"], alt: "BJJ 10" },
  { src: "assets/img/gallery/bjj-11.jpg", tags: ["BJJ"], alt: "BJJ 11" },
  { src: "assets/img/gallery/bjj-12.jpg", tags: ["BJJ"], alt: "BJJ 12" },
  { src: "assets/img/gallery/bjj-13.jpg", tags: ["BJJ"], alt: "BJJ 13" },
  { src: "assets/img/gallery/bjj-14.jpg", tags: ["BJJ"], alt: "BJJ 14" },
  { src: "assets/img/gallery/bjj-15.jpg", tags: ["BJJ"], alt: "BJJ 15" },
  { src: "assets/img/gallery/bjj-16.jpg", tags: ["BJJ"], alt: "BJJ 16" },
  { src: "assets/img/gallery/bjj-17.jpg", tags: ["BJJ"], alt: "BJJ 17" },
  { src: "assets/img/gallery/bjj-18.jpg", tags: ["BJJ"], alt: "BJJ 18" },
  { src: "assets/img/gallery/bjj-19.jpg", tags: ["BJJ"], alt: "BJJ 19" },
  { src: "assets/img/gallery/bjj-20.jpg", tags: ["BJJ"], alt: "BJJ 20" },
  { src: "assets/img/gallery/bjj-21.jpg", tags: ["BJJ"], alt: "BJJ 21" },
  { src: "assets/img/gallery/bjj-22.jpg", tags: ["BJJ"], alt: "BJJ 22" },
  { src: "assets/img/gallery/bjj-23.jpg", tags: ["BJJ"], alt: "BJJ 23" },
  { src: "assets/img/gallery/bjj-24.jpg", tags: ["BJJ"], alt: "BJJ 24" },
  { src: "assets/img/gallery/bjj-25.jpg", tags: ["BJJ"], alt: "BJJ 25" },
  { src: "assets/img/gallery/bjj-26.jpg", tags: ["BJJ"], alt: "BJJ 26" },
  { src: "assets/img/gallery/bjj-27.jpg", tags: ["BJJ"], alt: "BJJ 27" },
  { src: "assets/img/gallery/bjj-28.jpg", tags: ["BJJ"], alt: "BJJ 28" },
  { src: "assets/img/gallery/bjj-29.jpg", tags: ["BJJ"], alt: "BJJ 29" },
  { src: "assets/img/gallery/bjj-30.jpg", tags: ["BJJ"], alt: "BJJ 30" },
  { src: "assets/img/gallery/bjj-31.jpg", tags: ["BJJ"], alt: "BJJ 31" },
  { src: "assets/img/gallery/bjj-32.jpg", tags: ["BJJ"], alt: "BJJ 32" },
  { src: "assets/img/gallery/bjj-33.jpg", tags: ["BJJ"], alt: "BJJ 33" },
  { src: "assets/img/gallery/bjj-34.jpg", tags: ["BJJ"], alt: "BJJ 34" },
  { src: "assets/img/gallery/bjj-35.jpg", tags: ["BJJ"], alt: "BJJ 35" },
  { src: "assets/img/gallery/bjj-36.jpg", tags: ["BJJ"], alt: "BJJ 36" },
  { src: "assets/img/gallery/bjj-37.jpg", tags: ["BJJ"], alt: "BJJ 37" },
  { src: "assets/img/gallery/bjj-38.jpg", tags: ["BJJ"], alt: "BJJ 38" },
  { src: "assets/img/gallery/bjj-39.jpg", tags: ["BJJ"], alt: "BJJ 39" },
  { src: "assets/img/gallery/bjj-40.jpg", tags: ["BJJ"], alt: "BJJ 40" },
  { src: "assets/img/gallery/bjj-41.jpg", tags: ["BJJ"], alt: "BJJ 41" },
  { src: "assets/img/gallery/bjj-42.jpg", tags: ["BJJ"], alt: "BJJ 42" },
  { src: "assets/img/gallery/bjj-43.jpg", tags: ["BJJ"], alt: "BJJ 43" },
  { src: "assets/img/gallery/bjj-44.jpg", tags: ["BJJ"], alt: "BJJ 44" },
  { src: "assets/img/gallery/bjj-45.jpg", tags: ["BJJ"], alt: "BJJ 45" },
  { src: "assets/img/gallery/bjj-46.jpg", tags: ["BJJ"], alt: "BJJ 46" },
  { src: "assets/img/gallery/bjj-47.jpg", tags: ["BJJ"], alt: "BJJ 47" },
  { src: "assets/img/gallery/bjj-48.jpg", tags: ["BJJ"], alt: "BJJ 48" },
  { src: "assets/img/gallery/bjj-49.jpg", tags: ["BJJ"], alt: "BJJ 49" },
  { src: "assets/img/gallery/bjj-50.jpg", tags: ["BJJ"], alt: "BJJ 50" },
  { src: "assets/img/gallery/bjj-51.jpg", tags: ["BJJ"], alt: "BJJ 51" },
  { src: "assets/img/gallery/bjj-52.jpg", tags: ["BJJ"], alt: "BJJ 52" },
  { src: "assets/img/gallery/bjj-53.jpg", tags: ["BJJ"], alt: "BJJ 53" },
  { src: "assets/img/gallery/bjj-54.jpg", tags: ["BJJ"], alt: "BJJ 54" },
  { src: "assets/img/gallery/bjj-55.jpg", tags: ["BJJ"], alt: "BJJ 55" },
  { src: "assets/img/gallery/bjj-56.jpg", tags: ["BJJ"], alt: "BJJ 56" },
  { src: "assets/img/gallery/bjj-57.jpg", tags: ["BJJ"], alt: "BJJ 57" },
  { src: "assets/img/gallery/bjj-58.jpg", tags: ["BJJ"], alt: "BJJ 58" },
  { src: "assets/img/gallery/bjj-59.jpg", tags: ["BJJ"], alt: "BJJ 59" },
  { src: "assets/img/gallery/bjj-60.jpg", tags: ["BJJ"], alt: "BJJ 60" },
  { src: "assets/img/gallery/bjj-61.jpg", tags: ["BJJ"], alt: "BJJ 61" },
  { src: "assets/img/gallery/bjj-62.jpg", tags: ["BJJ"], alt: "BJJ 62" },
  { src: "assets/img/gallery/bjj-63.jpg", tags: ["BJJ"], alt: "BJJ 63" },
  { src: "assets/img/gallery/bjj-64.jpg", tags: ["BJJ"], alt: "BJJ 64" },
  { src: "assets/img/gallery/bjj-65.jpg", tags: ["BJJ"], alt: "BJJ 65" },
  { src: "assets/img/gallery/bjj-66.jpg", tags: ["BJJ"], alt: "BJJ 66" },
  { src: "assets/img/gallery/bjj-67.jpg", tags: ["BJJ"], alt: "BJJ 67" },
  { src: "assets/img/gallery/bjj-68.jpg", tags: ["BJJ"], alt: "BJJ 68" },
  { src: "assets/img/gallery/bjj-69.jpg", tags: ["BJJ"], alt: "BJJ 69" },
  { src: "assets/img/gallery/bjj-70.jpg", tags: ["BJJ"], alt: "BJJ 70" },
  { src: "assets/img/gallery/bjj-71.jpg", tags: ["BJJ"], alt: "BJJ 71" },
  { src: "assets/img/gallery/bjj-72.jpg", tags: ["BJJ"], alt: "BJJ 72" },
  { src: "assets/img/gallery/bjj-73.jpg", tags: ["BJJ"], alt: "BJJ 73" },
  { src: "assets/img/gallery/bjj-74.jpg", tags: ["BJJ"], alt: "BJJ 74" },
  { src: "assets/img/gallery/bjj-75.jpg", tags: ["BJJ"], alt: "BJJ 75" },
  { src: "assets/img/gallery/bjj-76.jpg", tags: ["BJJ"], alt: "BJJ 76" },
  { src: "assets/img/gallery/bjj-77.jpg", tags: ["BJJ"], alt: "BJJ 77" },
  { src: "assets/img/gallery/bjj-78.jpg", tags: ["BJJ"], alt: "BJJ 78" },
  { src: "assets/img/gallery/bjj-79.jpg", tags: ["BJJ"], alt: "BJJ 79" },
  { src: "assets/img/gallery/bjj-80.jpg", tags: ["BJJ"], alt: "BJJ 80" },
  { src: "assets/img/gallery/bjj-81.jpg", tags: ["BJJ"], alt: "BJJ 81" },
  { src: "assets/img/gallery/bjj-82.jpg", tags: ["BJJ"], alt: "BJJ 82" },
  { src: "assets/img/gallery/bjj-83.jpg", tags: ["BJJ"], alt: "BJJ 83" },
  { src: "assets/img/gallery/bjj-84.jpg", tags: ["BJJ"], alt: "BJJ 84" },
  { src: "assets/img/gallery/bjj-85.jpg", tags: ["BJJ"], alt: "BJJ 85" },
  { src: "assets/img/gallery/bjj-86.jpg", tags: ["BJJ"], alt: "BJJ 86" },
  { src: "assets/img/gallery/bjj-87.jpg", tags: ["BJJ"], alt: "BJJ 87" },
  { src: "assets/img/gallery/bjj-88.jpg", tags: ["BJJ"], alt: "BJJ 88" },
  { src: "assets/img/gallery/bjj-89.jpg", tags: ["BJJ"], alt: "BJJ 89" },
  { src: "assets/img/gallery/bjj-90.jpg", tags: ["BJJ"], alt: "BJJ 90" },
  { src: "assets/img/gallery/bjj-91.jpg", tags: ["BJJ"], alt: "BJJ 91" },
  { src: "assets/img/gallery/bjj-92.jpg", tags: ["BJJ"], alt: "BJJ 92" },
];
